{{- if .Values.global.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: web-ingress
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "robot-shop.labels" . | nindent 4 }}
    service: web
  {{- with .Values.global.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.global.ingress.className }}
  ingressClassName: {{ .Values.global.ingress.className }}
  {{- end }}
  rules:
  {{- range .Values.global.ingress.hosts }}
  - {{- if .host }}
    host: {{ .host }}
    {{- end }}
    http:
      paths:
      {{- range .paths }}
      - path: {{ .path }}
        pathType: {{ .pathType | default "Prefix" }}
        backend:
          service:
            name: {{ .service | default "web" }}
            port:
              number: {{ .port }}
      {{- end }}
  {{- end }}
{{- end }}
