image:
  repository: "{{ .Values.global.imageRegistry }}/dispatch"
  tag: "{{ .Values.global.imageTag }}"
  pullPolicy: "{{ .Values.global.imagePullPolicy }}"
service:
  type: ClusterIP
  port: 55555
resources:
  requests:
    cpu: 30m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 128Mi
