{{- $services := list "web" "cart" "catalogue" "user" "payment" "shipping" -}}
{{- range $service := $services }}
{{- $config := index $.Values $service }}
{{- if and $config.autoscaling $config.autoscaling.enabled }}
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ $service }}
  labels:
    service: {{ $service }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ $service }}
  minReplicas: {{ $config.autoscaling.minReplicas }}
  maxReplicas: {{ $config.autoscaling.maxReplicas }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ $config.autoscaling.targetCPUUtilizationPercentage }}
{{- end }}
{{- end }}
