apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd-hakimdevops-tls
  namespace: argocd
spec:
  secretName: argocd-hakimdevops-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
  - argocd.hakimdevops.art
