apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: hakimdevops-art-tls
  namespace: robot-shop
spec:
  secretName: hakimdevops-art-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
  - hakimdevops.art
