global:
  environment: dev
  monitoring:
    enabled: true
    namespace: monitoring

# Prometheus Stack Configuration
kube-prometheus-stack:
  fullnameOverride: "monitoring-dev"
  namespaceOverride: monitoring
  
  prometheus:
    ingress:
      enabled: true
      ingressClassName: nginx
      hosts:
        - prometheus.hakimdevops.art
  
  grafana:
    ingress:
      enabled: true
      ingressClassName: nginx
      hosts:
        - grafana.hakimdevops.art

alerts:
  enabled: true
  
dashboards:
  enabled: true

serviceMonitors:
  enabled: true

# Disable custom ingress to avoid conflicts
ingress:
  enabled: false
