apiVersion: v2
name: robot-shop
version: 1.2.0
appVersion: "1.0"
description: Microservices demo application for Azure AKS
type: application
keywords:
  - microservices
  - demo
  - azure
  - aks
  - robot-shop
home: https://github.com/instana/robot-shop
sources:
  - https://github.com/instana/robot-shop
